---

- name: "Running Prestashop role"
  debug: msg="project"
  when: prestashop == true
  changed_when: true

- name: Configure MySQL database
  lineinfile:
    dest: "{{ path }}/config/settings.inc.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "_DB_SERVER_", line: "define('_DB_SERVER_', '{{ mysql_host | mandatory }}');" }
    - { regexp: "_DB_NAME_",   line: "define('_DB_NAME_', '{{ mysql_database | mandatory }}');" }
    - { regexp: "_DB_USER_",   line: "define('_DB_USER_', '{{ mysql_username | default('root') }}');" }
    - { regexp: "_DB_PASSWD_", line: "define('_DB_PASSWD_', '{{ mysql_password | default('') }}');" }
  when: present == true and mysql == true and prestashop == true

- name: Configure base url in configuration table
  command: "mysql -e \"USE {{ mysql_database }}; UPDATE `ps_configuration` SET `value`='{{ nginx_host }}' WHERE `name` LIKE 'PS_SHOP_DOMAIN%' ;\""
  when: present == true and prestashop == true and prestashop_configurl
  changed_when: false

- name: Configure base url in shop table
  command: "mysql -e \"USE {{ mysql_database }}; UPDATE `ps_shop_url` SET `domain`='{{ nginx_host }}', `domain_ssl`=`domain` LIMIT 1;\""
  when: present == true and prestashop == true and prestashop_shopurl
  changed_when: false
