---

- name: Define default values
  set_fact:
    repo:       "{{ item.repo | default(false) }}"
    name:       "{{ item.name | default(item.repo | basename | regex_replace('.git$', '')) }}"
    project:    "{{ item.repo | basename | regex_replace('.git$', '') }}"
    path:       "{{ item.path | default(global.path + '/' + item.repo | basename | regex_replace('.git$', '')) | regex_replace('\\[\\[project\\]\\]', item.repo | basename | regex_replace('.git$', '')) }}"
    state:      "{{ item.state | default('present') }}"
    desk:       "{{ item.desk | default(false) }}"
    composer:   "{{ item.composer | default(false) }}"
    npm:        "{{ item.npm | default(false) }}"
    nginx:      "{{ item.nginx | default(false) }}"
    mysql:      "{{ item.mysql | default(false) }}"
    laravel:    "{{ item.laravel | default(false) }}"
    lumen:      "{{ item.lumen | default(false) }}"
    prestashop: "{{ item.prestashop | default(false) }}"
    wordpress:  "{{ item.wordpress | default(false) }}"
  with_items: projects
  register: items

- name: Print gathered facts values
  debug:
    var: items.results | map(attribute='ansible_facts') | list
  when: global.debug is defined and global.debug == true
