---

- name: Create virtualhosts
  template:
    src: "{{ item.nginx.template | default('default') }}"
    dest: "{{ global.nginx.path | default('/etc/nginx/vhosts') }}/{{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', item.project) }}"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("nginx", false) | list
  when: item.nginx != false
  register: create_virtualhost
  become: true

- name: Remove disabled projects virtualhosts
  file:
    path: "{{ global.nginx.path | default('/etc/nginx/vhosts') }}/{{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', item.project) }}"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
  register: remove_virtualhost

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: create_virtualhost.changed or remove_virtualhost.changed
  become: true

- name: Check if service php5-fpm exists
  stat: path=/etc/init.d/php5-fpm
  register: service_status
  when: create_virtualhost.changed or remove_virtualhost.changed

- name: Restart php5-fpm
  service:
    name: nginx
    state: restarted
  when: (create_virtualhost.changed or remove_virtualhost.changed) and service_status.stat.exists
  become: true
