---

- name: Create virtualhost
  template:
    src: "{{ item.nginx.template | default('default') }}"
    dest: "{{ item.path | default(path) }}/{{ item.repo | basename | regex_replace('.git$', '') }}.dev.conf"
    # dest: "/etc/nginx/sites-available/{{ item.repo | basename | regex_replace('.git$', '') }}.conf"
  with_items: projects | selectattr("state", "defined") | byattr("state", "present") | selectattr("nginx", "defined") | list
  when: item.nginx.install is defined and item.nginx.install == true
  register: create_virtualhost
  become: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: create_virtualhost.changed
  become: true

- name: Check if service php5-fpm exists
  stat: path=/etc/init.d/php5-fpm
  register: service_status
  when: create_virtualhost.changed

- name: Restart php5-fpm
  service:
    name: nginx
    state: restarted
  when: create_virtualhost.changed and service_status.stat.exists
  become: true
