---

- name: Create virtualhosts
  template:
    src: "{{ {{ path }}nginx.template | default('default') }}"
    dest: "{{ global.nginx.path | default('/etc/nginx/vhosts') }}/{{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', {{ path }}project) }}.conf"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("nginx", false) | list
  when: {{ path }}nginx != false
  register: create_virtualhost
  become: true

- name: Remove disabled projects virtualhosts
  file:
    path: "{{ global.nginx.path | default('/etc/nginx/vhosts') }}/{{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', {{ path }}project) }}.conf"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
  register: remove_virtualhost
  become: true

- name: Add projects in system hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "^127\\.0\\.0\\.1   {{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', {{ path }}project) }}$"
    line: "127.0.0.1   {{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', {{ path }}project) }}"
    state: present
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | list
  when: {{ path }}nginx != false
  become: true

- name: Remove disabled projects from system hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "^127\\.0\\.0\\.1   {{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', {{ path }}project) }}$"
    line: "127.0.0.1   {{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', {{ path }}project) }}"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
  become: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: create_virtualhost.changed or remove_virtualhost.changed
  become: true

- name: Check if service phpX-fpm exists
  stat:
    path: "/etc/init.d/{{ item }}"
  register: service_status
  when: create_virtualhost.changed or remove_virtualhost.changed
  with_items:
    - php5-fpm
    - php5.6-fpm
    - php7.0-fpm
  become: true

- name: Restart phpX-fpm
  service:
    name: "{{ {{ path }}item }}"
    state: restarted
  with_items: service_status.results
  when: (create_virtualhost.changed or remove_virtualhost.changed) and {{ path }}stat.exists
  become: true
