---

- name: Create virtualhosts
  template:
    src: "{{ item.nginx.template | default('default') }}"
    dest: "{{ global.nginx.path | default('/etc/nginx/vhosts') }}/{{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', item.project) }}"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("nginx", false) | list
  when: item.nginx != false
  register: create_virtualhost
  become: true

- name: Remove disabled projects virtualhosts
  file:
    path: "{{ global.nginx.path | default('/etc/nginx/vhosts') }}/{{ global.nginx.hostname | default('[[project]].dev') | regex_replace('\\[\\[project\\]\\]', item.project) }}"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
  register: remove_virtualhost

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: create_virtualhost.changed or remove_virtualhost.changed
  become: true

- name: Check if service phpX-fpm exists
  stat:
    path: "/etc/init.d/{{ item }}"
  register: service_status
  when: create_virtualhost.changed or remove_virtualhost.changed
  with_items:
    - php5-fpm
    - php5.6-fpm
    - php7.0-fpm

- name: Restart phpX-fpm
  service:
    name: "{{ item.item }}"
    state: restarted
  with_items: service_status.results
  when: (create_virtualhost.changed or remove_virtualhost.changed) and item.stat.exists
  become: true
