---

- name: "Running nginx role"
  debug: msg="project"
  when: nginx == true
  changed_when: true

- name: Create virtualhost
  template:
    src: "{{ nginx_template | mandatory }}"
    dest: "{{ nginx_conf | mandatory }}"
  when: present == true and nginx == true
  register: create_virtualhost
  become: true

- name: Remove disabled projects virtualhost
  file:
    path: "{{ nginx_conf | mandatory }}"
    state: absent
  register: remove_virtualhost
  when: present == false or nginx == false
  become: true

- name: Add projects in system hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "^127\\.0\\.0\\.1   {{ nginx_host }}$"
    line: "127.0.0.1   {{ nginx_host }}"
    state: present
  when: present == true and nginx == true
  become: true

- name: Remove disabled projects from system hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "^127\\.0\\.0\\.1   {{ nginx_host }}$"
    line: "127.0.0.1   {{ nginx_host }}"
    state: absent
  when: present == false or nginx == false
  become: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: create_virtualhost.changed or remove_virtualhost.changed
  become: true

- name: Check if service phpX-fpm exists
  stat:
    path: "/etc/init.d/{{ item }}"
  register: service_status
  when: create_virtualhost.changed or remove_virtualhost.changed
  with_items:
    - php5-fpm
    - php5.6-fpm
    - php7.0-fpm
  become: true

- name: Restart phpX-fpm
  service:
    name: "{{ item.item }}"
    state: restarted
  with_items: "{{ service_status.results }}"
  when: (create_virtualhost.changed or remove_virtualhost.changed) and item.stat.exists
  become: true
