---

- name: "Running Laravel role"
  debug: msg="project"
  when: laravel
  changed_when: true

- name: Create .env file
  copy:
    src: "{{ path }}/.env.example"
    dest: "{{ path }}/.env"
    force: no
  register: create_env_file
  when: present and laravel

- name: Generate a new key
  command: php artisan key:generate
  args:
    chdir: "{{ path }}"
  when: create_env_file.changed and laravel_key

- name: Configure MySQL database
  lineinfile:
    dest: "{{ path }}/.env"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^DB_HOST=",     line: "DB_HOST={{ mysql_host | mandatory }}" }
    - { regexp: "^DB_DATABASE=", line: "DB_DATABASE={{ mysql_database | mandatory }}" }
    - { regexp: "^DB_USERNAME=", line: "DB_USERNAME={{ mysql_username | default('root') }}" }
    - { regexp: "^DB_PASSWORD=", line: "DB_PASSWORD={{ mysql_password | default('') }}" }
  when: present and mysql and laravel

- name: Generate a new application key
  command: php artisan key:generate
  args:
    chdir: "{{ path }}"
  when: create_env_file.changed and laravel_key

- name: Migrate database
  command: "php artisan migrate"
  args:
    chdir: "{{ path }}"
  when: create_env_file.changed and laravel_migrate

- name: Seed database
  command: "php artisan db:seed"
  args:
    chdir: "{{ path }}"
  when: create_env_file.changed and laravel_seed
