---

global:
  path: "/path/to/projects"
  mysql:
    user: "root"
    password: "root"
  npm:
    options: "--no-bin-links"
  nginx:
    path: "/etc/nginx/vhosts"
    hostname: "[[project]].dev"
    fastcgi: "/var/run/php5-fpm.sock"
projects:
  - repo:  "git@github.com:vendor/project-minimal.git"

  - name:  "Name of the first project"
    repo:  "git@github.com:vendor/project1.git"
    path:  "{{global.path}}/subdirectory/[[project]]"
    state: "present"
    nginx: { root: "public" }
    desk:  true

  - name:  "Name of the 2nd project"
    repo:  "git@github.com:vendor/project2.git"
    state: "absent"

  - name:       "Name of the third project"
    repo:       "git@github.com:vendor/project3.git"
    state:      "present"
    desk:       { template: "web" }
    composer:   true
    npm:        true
    nginx:      { template: "prestashop16" }
    mysql:      { import: "sql/dump.sql" }
    laravel:    { key: true, migrate: true, seed: true }
    lumen:      { key: true, migrate: true, seed: true }
    prestashop: { configurl: true, shopurl: true }
    wordpress:  true
