---

- hosts: localhost
  gather_facts: false
  vars_files:
    - "_global_variables.yml"
    - "{{ projects_path | mandatory }}/_projects_variables.yml"
    - "{{ projects_path | mandatory }}/{{ project | mandatory }}.yml"
  roles:
    - prepare-values
    - git
    - desk
    - composer
    - npm
    - mysql
    - nginx
    # - fuelphp
    # - laravel
    # - prestashop
    # - wordpress
