---

- hosts: localhost
  vars_files:
    - "{{ config_file | mandatory }}"
  roles:
    # - git
    # - desk
    # - composer
    # - npm
    # - nginx
    # - mysql
    # - laravel
    # - lumen
    # - prestashop
    # - wordpress
