---

- hosts: localhost
  vars_files:
    - "_global_variables.yml"
    - "{{ projects_path | mandatory }}/_group_variables.yml"
    - "{{ projects_path | mandatory }}/{{ project | mandatory }}.yml"
  roles:
    - prepare-values
    - { role: git, when: git != "" }
    - { role: desk, when: desk != "" }
    - { role: composer, when: composer != "" }
    - { role: npm, when: npm != "" }
    - { role: mysql, when: mysql != "" }
    - { role: nginx, when: nginx != "" }
    - { role: fuelphp, when: fuelphp != "" }
    - { role: laravel, when: laravel != "" }
    - { role: prestashop, when: prestashop != "" }
    - { role: wordpress, when: wordpress != "" }
