---

- hosts: localhost
  vars_files:
    - "{{ config_file | mandatory }}"
  roles:
    - setfacts
    - git
    - desk
    - composer
    - npm
    - mysql
    # - nginx
    # - laravel
    # - lumen
    # - prestashop
    # - wordpress
