---

- name: "Running NPM role"
  debug: msg="project"
  when: npm
  changed_when: true

- name: "Install \"{{ project }}\" packages"
  command: "npm install {{ npm_options }}"
  args:
    chdir: "{{ path }}"
  when: present and npm
