---

- name: "Running NPM role"
  debug: msg="project"
  when: npm == true
  changed_when: true

- name: "Check if node_modules directory exist"
  stat:
    path: "{{ path }}/node_modules"
    follow: true
  register: node_modules_exist

- name: "Install packages"
  command: "npm install {{ npm_options }}"
  args:
    chdir: "{{ path }}"
  when: present == true and npm == true and node_modules_exist.stat.exists == false
