---

- name: Install packages
  command: "npm install {{ global.npm.options | default('') }}"
  args:
    chdir: "{{ item.path }}"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | selectattr("npm", "defined") | list
  when: item.npm != false
