---

- name: Install packages
  command: "npm install {{ global.npm.options | default('') }}"
  args:
    chdir: "{{ path }}"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("npm", false) | list
  when: npm != false
