---

- name: Configure database name
  replace:
    dest: "{{ item.path }}/wp-config.php"
    regexp: "(.*)DB_NAME(.*)"
    replace: "define('DB_NAME', '{{ item.mysql.database | default(item.project) }}');"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("wordpress", false) | list
  when: item.wordpress != false

- name: Configure database username
  replace:
    dest: "{{ item.path }}/wp-config.php"
    regexp: "(.*)DB_USER(.*)"
    replace: "define('DB_USER', '{{ global.mysql.user | default('root') }}');"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("wordpress", false) | list
  when: item.wordpress != false

- name: Configure database password
  replace:
    dest: "{{ item.path }}/wp-config.php"
    regexp: "(.*)DB_PASSWORD(.*)"
    replace: "define('DB_PASSWORD', '{{ global.mysql.password | default('') }}');"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("wordpress", false) | list
  when: item.wordpress != false
