---

- name: "Running FuelPHP role"
  debug: msg="project"
  when: fuelphp == true
  changed_when: true

- name: Configure base URL
  replace:
    dest: "{{ path }}/fuel/app/config/development/config.php"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "(.*)'base_url'(.*)", replace: "    'base_url' => {{ fuelphp_base_url }}," }
  when: present == true and fuelphp == true

- name: Configure MySQL database
  replace:
    dest: "{{ path }}/fuel/app/config/development/db.php"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: "(.*)'dsn'(.*)",      replace: "                    'dsn' => 'mysql:host={{ mysql_host | mandatory }};dbname={{ mysql_database | mandatory }}'," }
    - { regexp: "(.*)'username'(.*)", replace: "                    'username' => '{{ mysql_username | default('root') }}'," }
    - { regexp: "(.*)'password'(.*)", replace: "                    'password' => '{{ mysql_password | default('') }}'," }
  when: present == true and mysql == true and fuelphp == true
