---

- name: "Running MySQL role"
  debug: msg="project"
  when: mysql == true
  changed_when: true

- name: "Create database"
  mysql_db:
    name: "{{ mysql_database | mandatory }}"
    state: present
  when: present == true and mysql == true
  register: database_created

- name: "Import dumps"
  mysql_db:
    name: "{{ mysql_database }}"
    state: import
    target: "{{ item }}"
  with_items: "{{ mysql_imports }}"
  when: present == true and mysql == true and database_created.changed

- name: "Remove database"
  mysql_db:
    name: "{{ mysql_database }}"
    state: absent
  when: present == false or mysql == false
