---

- name: "Running MySQL role"
  debug: msg="project"
  when: mysql
  changed_when: true

- name: "Create \"{{ project }}\" database"
  mysql_db:
    name: "{{ mysql_database | mandatory }}"
    state: present
  when: present and mysql
  register: database_created

- name: "Import \"{{ project }}\" dumps"
  mysql_db:
    name: "{{ mysql_database }}"
    state: import
    target: "{{ item }}"
  with_items: mysql_imports
  when: present and mysql and database_created.changed

- name: "Remove \"{{ project }}\" database"
  mysql_db:
    name: "{{ mysql_database }}"
    state: absent
  when: present == false or mysql == false
