---

- name: Create databases
  mysql_db:
    name: "{{ item.project }}"
    state: present
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | selectattr("mysql", "defined") | list
  when: item.mysql.install is defined and item.mysql.install == true
  register: database_created

- name: Import dumps
  mysql_db:
    name: "{{ item.item.project }}"
    state: import
    target: "{{ item.item.mysql.import }}"
  with_items: database_created.results | byattr("changed", true)
  when: database_created.changed and item.item.mysql.import is defined

- name: Remove and clean databases
  mysql_db:
    name: "{{ item.project }}"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
