---

- name: Install packages
  composer:
    working_dir: "{{ {{ path }}path }}"
    command: "install"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("composer", false) | list
  when: {{ path }}composer != false
