---

- name: "Running Composer role"
  debug: msg="project"
  when: composer
  changed_when: true

- name: "Install \"{{ project }}\" packages"
  composer:
    working_dir: "{{ path }}"
    command: "install"
  when: present and composer
