---

- name: "Running Composer role"
  debug: msg="project"
  when: composer == true
  changed_when: true

- name: "Check if vendor directory exist"
  stat:
    path: "{{ path }}/vendor"
    follow: true
  register: vendor_exist

- name: "Install packages"
  composer:
    working_dir: "{{ path }}"
    command: "install"
    no-dev: "no"
  when: present == true and composer == true and vendor_exist.stat.exists == false
