---

- name: Install packages
  composer:
    working_dir: "{{ item.path | default(path) }}/{{ item.repo | basename | regex_replace('.git$', '') }}"
    command: "install"
  with_items: projects | selectattr("state", "defined") | byattr("state", "present") | selectattr("composer", "defined") | list
  when: item.composer.install is defined and item.composer.install == true
