---

- name: "Check if {{ project }} repository exist"
  stat:
    path: "{{ path }}/.git"
    follow: true
  register: repository_exist

- name: "Clone {{ project }} repository"
  git:
    repo: "{{ git_repository }}"
    dest: "{{ path }}"
    accept_hostkey: true
  when: present and git and repository_exist.stat.exists == false

- name: "Remove disabled {{ project }} repository"
  file:
    path: "{{ path }}"
    state: absent
  when: (present == false or git == false) and repository_exist.stat.exists == true

# @todo configure git repository with "git_username" and "git_email"
