---

- name: Check if repositories exists
  stat:
    path: "{{ item.path }}/.git"
    follow: true
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | list
  register: repository_exist
  when: item.repo != false

- name: Clone repositories
  git:
    repo: "{{ item.item.repo }}"
    dest: "{{ item.item.path }}"
    accept_hostkey: true
  with_items: repository_exist.results
  when: item.item.repo != false and item.stat.exists == false

- name: Remove disabled projects repositories
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
