---

- name: Clone repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    accept_hostkey: true
  ignore_errors: yes
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | list
  when: item.repo != false

- name: Remove disabled projects repositories
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
