---

- name: Create Deskfiles
  template:
    src: "{{ item.desk.template | default('default') }}"
    dest: "~/.desk/desks/{{ item.project }}.sh"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("desk", false) | list
  when: item.desk != false

- name: Remove and clean Deskfiles
  file:
    path: "~/.desk/desks/{{ item.project }}.sh"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
