---

- name: "Create \"{{ project }}\" Deskfile"
  template:
    src: "{{ desk_template }}"
    dest: "~/.desk/desks/{{ project }}.sh"
  when: present and desk

- name: "Remove \"{{ project }}\" Deskfile"
  file:
    path: "~/.desk/desks/{{ project }}.sh"
    state: absent
  when: present == false or desk == false
