---

- name: Create Deskfiles
  template:
    src: "{{ {{ path }}desk.template | default('default') }}"
    dest: "~/.desk/desks/{{ {{ path }}project }}.sh"
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "present") | notbyattr("desk", false) | list
  when: {{ path }}desk != false

- name: Remove and clean Deskfiles
  file:
    path: "~/.desk/desks/{{ {{ path }}project }}.sh"
    state: absent
  with_items: items.results | map(attribute='ansible_facts') | byattr("state", "absent") | list
