---

- name: "Running Desk role"
  debug: msg="project"
  when: desk
  changed_when: true

- name: "Create Deskfile"
  template:
    src: "{{ desk_template }}"
    dest: "~/.desk/desks/{{ project }}.sh"
  when: present and desk

- name: "Remove Deskfile"
  file:
    path: "~/.desk/desks/{{ project }}.sh"
    state: absent
  when: present == false or desk == false
