---

- name: "Playbook for project \"{{ project }}\""
  debug: msg="project"
  changed_when: true

- name: "Add missing values on \"{{ project }}\""
  set_fact:
    root:       "{{ root       | mandatory }}"
    path:       "{{ path       | mandatory }}"
    project:    "{{ project    | mandatory }}"
    name:       "{{ name       | default(project) | mandatory }}"
    present:    "{{ present    | mandatory }}"
    git:        "{{ git        | mandatory }}"
    desk:       "{{ desk       | mandatory }}"
    composer:   "{{ composer   | mandatory }}"
    npm:        "{{ npm        | mandatory }}"
    mysql:      "{{ mysql      | mandatory }}"
    nginx:      "{{ nginx      | mandatory }}"
    fuelphp:    "{{ fuelphp    | mandatory }}"
    laravel:    "{{ laravel    | mandatory }}"
    prestashop: "{{ prestashop | mandatory }}"
    wordpress:  "{{ wordpress  | mandatory }}"

# - name: Debug value
#   debug: var=git
