---

- name: "Add missing values on \"{{ project }}\""
  set_fact:
    root:    "{{ root | mandatory }}"
    project: "{{ project | mandatory }}"
    name:    "{{ name | default(project) | mandatory }}"
    path:    "{{ path | mandatory }}"
    present: "{{ present | mandatory }}"

    desk_template: "{{ desk_template | default('default') }}"

# - name: Debug value
#   debug: var=git
